package com.knorex.productservice.models;

import com.knorex.productservice.Constants.ProductCategory;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

@Entity
public class Product extends Auditable {

    // Autogenerated Primary Key Id
    @Id
    @GeneratedValue
    private int id;

    // Data Fields
    @NotNull(message = "Name can't be null")
    @NotBlank(message = "Name can't be blank")
    private String name;
    private ProductCategory category = ProductCategory.ELECTRONICS;
    @NotNull
    private int price;

    // Getters and Setters

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ProductCategory getCategory() {
        return category;
    }

    public void setCategory(ProductCategory category) {
        this.category = category;
    }

    public int getPrice() {
        return price;
    }

    public void setPrice(int price) {
        this.price = price;
    }
}
